application: ravenwildegir
version: 1

runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|css|js))
  static_files: \1
  upload: .*\.(gif|png|jpg|ico|css|js)
- url: /.*
  script: index.app
  secure: always
